version: 1.2
workflows:
  - subclass: WDL
    name: projected_admixture
    primaryDescriptorPath: projected_admixture.wdl
    authors: 
      - orcid: 0000-0002-7989-5420
    # testParameterFiles:
    #   - /projected_admixture.wdl
    #  - subclass: WDL
    #    name: basic_Admixture
    #    primaryDescriptorPath: /basic_Admixture.wdl
    #    authors:
    #      - orcid: 0000-0002-7980-5420
